- name: Check if cargo is Installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Rust
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /home/jpedro/.ansible/tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: Install Rust/Cargo
  when: cargo_exists is failed
  shell: /home/jpedro/.ansible/tmp/sh.rustup.rs -y
  tags:
    -rust
